In this simple notebook we perform the cleaning of our data in Medallion architecture.

# Setup

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

# basic manipulation path tools
import os
from pathlib import Path
notebook_path = Path().absolute()
project_root = notebook_path.parent
notebook_path = Path().absolute()
project_root = notebook_path.parent

In [2]:
# Safely create 'data' directory and subdirectories only if they don't exist
data_dir = os.path.join(project_root, 'data')
bronze_dir = os.path.join(data_dir, 'bronze')
silver_dir = os.path.join(data_dir, 'silver')
gold_dir = os.path.join(data_dir, 'gold')

if not os.path.isdir(data_dir):
    os.makedirs(bronze_dir)
    os.makedirs(silver_dir)
    os.makedirs(gold_dir)
    print(f"Created data directory structure at: {data_dir}")
    print(f"Subdirectories created: bronze, silver, gold")
else:
    # Create subdirectories if they don't exist (even if data_dir exists)
    for subdir in [bronze_dir, silver_dir, gold_dir]:
        os.makedirs(subdir, exist_ok=True)
    print(f"Data directory structure exists at: {data_dir}")

Data directory structure exists at: /home/dmitry/Projects/star_classification/data

# 1. Bronze Layer

In [3]:
# Resolve absolute path to the script
extract_path = project_root / "scripts" / "data_extract.py"

# Run the script
%run "{extract_path}"

WARNING: W02: ?:?:?: W02: '' is not a valid datatype according to the VOSI spec [pyvo.io.vosi.vodataservice]

In [4]:
dfB = pd.read_csv(project_root/'data'/'bronze'/'starB.csv')
dfB

,recno,ObsID,Target,Obs_Date,LMJD,MJD,PlanId,spId,FiberId,RAJ2000,...,Teff,e_Teff,logg,e_logg,[Fe/H],e_[Fe/H],RV,e_RV,GaiaDR2,Gmag
0,3058469,300702165,J030001.08+000110.8,2457042.0,57043,57042,EG030739N012421M01,2,165,45.004509,...,4729.36,118.22,4.741,0.193,-0.128,0.114,42.15,4.07,3.865554e+10,14.140491
1,1671,215109,J030001.01+000115.4,2455858.0,55859,55858,F5907,15,109,45.004220,...,4642.57,138.19,4.662,0.227,-0.363,0.134,36.61,5.25,3.436113e+10,17.604027
2,91644,18112111,J030001.01+000115.4,2455914.0,55915,55914,F5591503,12,111,45.004220,...,4664.49,197.81,4.690,0.315,-0.207,0.186,35.04,4.61,3.436113e+10,17.604027
3,3626193,367412199,J030011.58+000253.9,2457303.0,57304,57303,EG025335S013827B01,12,199,45.048267,...,4960.44,42.96,4.613,0.071,-0.262,0.041,-35.46,3.81,5.497558e+11,15.003798
4,91657,18112179,J025958.38+000434.8,2455914.0,55915,55914,F5591503,12,179,44.993274,...,5371.04,322.99,4.296,0.533,-0.248,0.307,-29.91,8.60,1.275606e+12,16.246628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,5852005,686002046,J040439.52+143334.1,2458422.0,58423,58422,TD041055N155647B01,2,46,61.164671,...,6061.88,12.27,3.811,0.020,-0.240,0.011,9.94,4.85,3.909111e+16,11.743764
49996,3799840,381902037,J040433.29+143347.3,2457329.0,57330,57329,GAC062N15B1,2,37,61.138728,...,6033.30,159.34,4.190,0.257,-0.458,0.152,35.12,8.61,3.909115e+16,15.094511
49997,3799843,381902043,J040422.34+143316.6,2457329.0,57330,57329,GAC062N15B1,2,43,61.093112,...,5066.79,193.49,3.210,0.306,-0.247,0.183,-26.94,4.92,3.909128e+16,15.418423
49998,2498732,254204018,J040423.20+143345.7,2456945.0,56946,56945,HD040531N141710V01,4,18,61.096676,...,5571.65,37.31,4.073,0.062,0.435,0.035,1.68,3.93,3.909132e+16,13.215559
49999,6045768,724304018,J040423.20+143345.7,2458522.0,58523,58522,HD040531N141710V02,4,18,61.096676,...,5558.18,45.69,4.045,0.075,0.406,0.044,4.15,4.97,3.909132e+16,13.215559

Let's inspect the informations of our data. We begin by inspecting its datatypes, NaN values and summary.

In [5]:
dfB.columns

Index(['recno', 'ObsID', 'Target', 'Obs_Date', 'LMJD', 'MJD', 'PlanId', 'spId',
       'FiberId', 'RAJ2000', 'DEJ2000', 'snru', 'snrg', 'snrr', 'snri', 'snrz',
       'objType', 'Class', 'subClass', 'z', 'e_z', 'magType', 'mag1', 'mag2',
       'mag3', 'mag4', 'mag5', 'mag6', 'mag7', 'tsource', 'FiberType', 'tfrom',
       'tcomment', 'offsets', 'offsetsv', 'RAOdeg', 'DEOdeg', 'Teff', 'e_Teff',
       'logg', 'e_logg', '[Fe/H]', 'e_[Fe/H]', 'RV', 'e_RV', 'GaiaDR2',
       'Gmag'],
      dtype='object')

In [6]:
dfB.dtypes

recno          int64
ObsID          int64
Target        object
Obs_Date     float64
LMJD           int64
MJD            int64
PlanId        object
spId           int64
FiberId        int64
RAJ2000      float64
DEJ2000      float64
snru         float64
snrg         float64
snrr         float64
snri         float64
snrz         float64
objType       object
Class         object
subClass      object
z            float64
e_z          float64
magType       object
mag1         float64
mag2         float64
mag3         float64
mag4         float64
mag5         float64
mag6         float64
mag7         float64
tsource       object
FiberType     object
tfrom         object
tcomment      object
offsets        int64
offsetsv     float64
RAOdeg       float64
DEOdeg       float64
Teff         float64
e_Teff       float64
logg         float64
e_logg       float64
[Fe/H]       float64
e_[Fe/H]     float64
RV           float64
e_RV         float64
GaiaDR2      float64
Gmag         float64
dtype: object

The dataset contains lots of columns that will not be of use in stellar classification, mainly the errors like 'e_FeH1'. Furthermore, the labels of the columns are not into proper snake_case formating, which is convenient for later analysis. We now turn to implement this considerations into the silver layer of our Data Lakehouse.

# 2. Silver Layer

In [7]:
# Resolve absolute path to the script
silver_path = project_root / "scripts" / "silver.py"

# Run the script
%run "{silver_path}"
dfS = pd.read_csv(project_root/'data'/'silver'/'starS.csv')
dfS

,recno,observation_id,target_name,observation_date,local_mjd,modified_julian_date,plan_id,spectrum_id,fiber_id,ra_j2000,...,effective_temperature,effective_temperature_error,log_surface_gravity,log_surface_gravity_error,metallicity_fe_h,metallicity_fe_h_error,radial_velocity,radial_velocity_error,gaia_dr2_id,gaia_g_magnitude
0,3058469,300702165,J030001.08+000110.8,2457042.0,57043,57042,EG030739N012421M01,2,165,45.004509,...,4729.36,118.22,4.741,0.193,-0.128,0.114,42.15,4.07,3.865554e+10,14.140491
1,1671,215109,J030001.01+000115.4,2455858.0,55859,55858,F5907,15,109,45.004220,...,4642.57,138.19,4.662,0.227,-0.363,0.134,36.61,5.25,3.436113e+10,17.604027
2,91644,18112111,J030001.01+000115.4,2455914.0,55915,55914,F5591503,12,111,45.004220,...,4664.49,197.81,4.690,0.315,-0.207,0.186,35.04,4.61,3.436113e+10,17.604027
3,3626193,367412199,J030011.58+000253.9,2457303.0,57304,57303,EG025335S013827B01,12,199,45.048267,...,4960.44,42.96,4.613,0.071,-0.262,0.041,-35.46,3.81,5.497558e+11,15.003798
4,91657,18112179,J025958.38+000434.8,2455914.0,55915,55914,F5591503,12,179,44.993274,...,5371.04,322.99,4.296,0.533,-0.248,0.307,-29.91,8.60,1.275606e+12,16.246628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,5852005,686002046,J040439.52+143334.1,2458422.0,58423,58422,TD041055N155647B01,2,46,61.164671,...,6061.88,12.27,3.811,0.020,-0.240,0.011,9.94,4.85,3.909111e+16,11.743764
49996,3799840,381902037,J040433.29+143347.3,2457329.0,57330,57329,GAC062N15B1,2,37,61.138728,...,6033.30,159.34,4.190,0.257,-0.458,0.152,35.12,8.61,3.909115e+16,15.094511
49997,3799843,381902043,J040422.34+143316.6,2457329.0,57330,57329,GAC062N15B1,2,43,61.093112,...,5066.79,193.49,3.210,0.306,-0.247,0.183,-26.94,4.92,3.909128e+16,15.418423
49998,2498732,254204018,J040423.20+143345.7,2456945.0,56946,56945,HD040531N141710V01,4,18,61.096676,...,5571.65,37.31,4.073,0.062,0.435,0.035,1.68,3.93,3.909132e+16,13.215559
49999,6045768,724304018,J040423.20+143345.7,2458522.0,58523,58522,HD040531N141710V02,4,18,61.096676,...,5558.18,45.69,4.045,0.075,0.406,0.044,4.15,4.97,3.909132e+16,13.215559

In [8]:
dfS.columns

Index(['recno', 'observation_id', 'target_name', 'observation_date',
       'local_mjd', 'modified_julian_date', 'plan_id', 'spectrum_id',
       'fiber_id', 'ra_j2000', 'de_j2000', 'signal_to_noise_u',
       'signal_to_noise_g', 'signal_to_noise_r', 'signal_to_noise_i',
       'signal_to_noise_z', 'object_type', 'type', 'full_class', 'redshift',
       'redshift_error', 'magnitude_type', 'magnitude_u', 'magnitude_g',
       'magnitude_r', 'magnitude_i', 'magnitude_z', 'magnitude_j',
       'magnitude_h', 'target_source', 'fiber_type', 'target_origin',
       'target_comment', 'position_offset', 'velocity_offset',
       'observed_ra_deg', 'observed_dec_deg', 'effective_temperature',
       'effective_temperature_error', 'log_surface_gravity',
       'log_surface_gravity_error', 'metallicity_fe_h',
       'metallicity_fe_h_error', 'radial_velocity', 'radial_velocity_error',
       'gaia_dr2_id', 'gaia_g_magnitude'],
      dtype='object')

The silver layer DataFrame is now formatted in the standard snake_case convention, useful for data analyses. We now turn to visualize some of its characteristics.

In [9]:
print(len(dfS))
dfS.describe(include='all')

50000

,recno,observation_id,target_name,observation_date,local_mjd,modified_julian_date,plan_id,spectrum_id,fiber_id,ra_j2000,...,effective_temperature,effective_temperature_error,log_surface_gravity,log_surface_gravity_error,metallicity_fe_h,metallicity_fe_h_error,radial_velocity,radial_velocity_error,gaia_dr2_id,gaia_g_magnitude
count,5.000000e+04,5.000000e+04,50000,5.000000e+04,50000.000000,50000.000000,50000,50000.000000,50000.000000,50000.000000,...,50000.000000,49995.000000,50000.000000,49979.000000,50000.000000,49996.000000,50000.000000,49995.000000,4.982400e+04,49824.000000
unique,NaN,NaN,45463,NaN,NaN,NaN,101,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,J023410.98+054031.5,NaN,NaN,NaN,EG030152N052010B01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,9,NaN,NaN,NaN,1921,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,3.225091e+06,3.338839e+08,NaN,2.457158e+06,57158.855800,57157.855800,NaN,8.584600,126.743680,46.053373,...,5418.996364,141.366808,4.208012,0.225745,-0.319481,0.133527,-3.850553,6.232724,1.888684e+16,15.105522
std,1.368520e+06,1.463574e+08,NaN,5.160375e+02,516.037529,516.037529,NaN,4.567076,70.667696,5.682566,...,651.463290,100.327807,0.558272,0.158097,0.363398,0.094686,46.335607,2.796653,1.215833e+16,1.998179
min,1.394000e+03,2.090790e+05,NaN,2.455858e+06,55859.000000,55858.000000,NaN,1.000000,1.000000,33.797756,...,3782.120000,6.700000,0.299000,0.009000,-2.470000,0.005000,-370.090000,0.690000,3.436113e+10,7.673463
25%,2.732011e+06,2.692020e+08,NaN,2.456981e+06,56982.000000,56981.000000,NaN,5.000000,67.000000,41.634838,...,4966.485000,46.805000,4.096000,0.077000,-0.511000,0.045000,-26.552500,4.360000,7.577074e+15,13.627618
50%,3.124046e+06,3.089032e+08,NaN,2.457053e+06,57054.000000,57053.000000,NaN,9.000000,127.000000,45.368725,...,5519.350000,136.930000,4.303000,0.219000,-0.291000,0.130000,-1.510000,5.500000,1.877219e+16,15.206289
75%,4.089400e+06,4.148061e+08,NaN,2.457414e+06,57415.000000,57414.000000,NaN,12.000000,187.000000,49.369067,...,5880.872500,211.370000,4.565000,0.335000,-0.071000,0.199000,22.560000,7.295000,3.018133e+16,17.014022
max,6.046356e+06,7.243140e+08,NaN,2.458522e+06,58523.000000,58522.000000,NaN,16.000000,250.000000,61.810213,...,8443.100000,981.120000,4.899000,1.198000,0.770000,0.961000,384.780000,79.070000,3.909132e+16,20.828840

In [10]:
dfS.isna().sum()

recno                              0
observation_id                     0
target_name                        0
observation_date                   0
local_mjd                          0
modified_julian_date               0
plan_id                            0
spectrum_id                        0
fiber_id                           0
ra_j2000                           0
de_j2000                           0
signal_to_noise_u                 13
signal_to_noise_g                  0
signal_to_noise_r                  0
signal_to_noise_i                 72
signal_to_noise_z                 55
object_type                        5
type                               0
full_class                         0
redshift                           0
redshift_error                     0
magnitude_type                     0
magnitude_u                      568
magnitude_g                      415
magnitude_r                      389
magnitude_i                    41815
magnitude_z                    43477
magnitude_j                    45369
magnitude_h                    45371
target_source                      0
fiber_type                         0
target_origin                      0
target_comment                     0
position_offset                    0
velocity_offset                    0
observed_ra_deg                    0
observed_dec_deg                   0
effective_temperature              0
effective_temperature_error        5
log_surface_gravity                0
log_surface_gravity_error         21
metallicity_fe_h                   0
metallicity_fe_h_error             4
radial_velocity                    0
radial_velocity_error              5
gaia_dr2_id                      176
gaia_g_magnitude                 176
dtype: int64

As one may observe, the 'lamost' entry has one unique register for each data, being essentially an identifier of the object in the ski. This information may therefore be used as an interesting feature to implement a hard key in the gold layer. Furthermore, the data contains missing values for most of its columns, which must be properly dealt with.

In [11]:
dfS.dropna().describe(include='all')

,recno,observation_id,target_name,observation_date,local_mjd,modified_julian_date,plan_id,spectrum_id,fiber_id,ra_j2000,...,effective_temperature,effective_temperature_error,log_surface_gravity,log_surface_gravity_error,metallicity_fe_h,metallicity_fe_h_error,radial_velocity,radial_velocity_error,gaia_dr2_id,gaia_g_magnitude
count,4.044000e+03,4.044000e+03,4044,4.044000e+03,4044.000000,4044.000000,4044,4044.000000,4044.000000,4044.000000,...,4044.000000,4044.000000,4044.000000,4044.000000,4044.000000,4044.000000,4044.000000,4044.000000,4.044000e+03,4044.000000
unique,NaN,NaN,3342,NaN,NaN,NaN,53,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,J023410.98+054031.5,NaN,NaN,NaN,EG025613N082253V01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,9,NaN,NaN,NaN,875,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,9.477497e+05,1.136092e+08,NaN,2.456379e+06,56380.354105,56379.354105,NaN,10.017062,126.587537,45.549968,...,5555.247282,124.095729,4.045087,0.198234,-0.219383,0.117074,-1.041929,6.156063,1.641297e+16,13.451037
std,1.100227e+06,1.142348e+08,NaN,3.957733e+02,395.773262,395.773262,NaN,4.409864,71.908494,4.573944,...,638.188395,107.967713,0.640404,0.172244,0.338785,0.101901,41.408371,2.970478,1.070056e+16,1.858014
min,1.487000e+03,2.110090e+05,NaN,2.455858e+06,55859.000000,55858.000000,NaN,1.000000,1.000000,36.689690,...,3852.520000,7.950000,0.299000,0.011000,-2.328000,0.006000,-354.210000,0.970000,3.436113e+10,8.188991
25%,4.127108e+05,5.710516e+07,NaN,2.456201e+06,56202.000000,56201.000000,NaN,7.000000,65.000000,42.510521,...,5104.702500,42.615000,3.958000,0.070000,-0.391000,0.041000,-22.770000,4.357500,7.242822e+15,12.254222
50%,4.998715e+05,7.620202e+07,NaN,2.456232e+06,56233.000000,56232.000000,NaN,11.000000,126.000000,45.471863,...,5647.790000,96.940000,4.196000,0.156000,-0.179500,0.093000,1.880000,5.450000,1.569458e+16,13.242906
75%,7.564142e+05,1.028122e+08,NaN,2.456298e+06,56299.000000,56298.000000,NaN,13.000000,190.000000,47.895286,...,6008.882500,163.377500,4.426000,0.258000,0.005000,0.153000,23.227500,7.060000,2.772761e+16,14.506678
max,5.608122e+06,6.332162e+08,NaN,2.458137e+06,58138.000000,58137.000000,NaN,16.000000,250.000000,61.810213,...,8310.590000,748.830000,4.895000,1.198000,0.653000,0.711000,294.440000,47.800000,3.905438e+16,20.828840

# 3. Gold Layer

In the gold layer, we combine the 'date' and 'lamost' columns into a single 'identifier' column, which is an interesting hard key for our data. Said feature contains information pertaining both to the object itself in 'lamost' and its date, which will is useful to update the dataset. Apart from the missing values, which must be handled in different ways depending on the analysis, the dataset is now ready to be visualized and analyzed, which we implement in the data_visualization.ipynb notebook.

In [12]:
# Resolve absolute path to the script
gold_path = project_root / "scripts" / "gold.py"

# Run the script
%run "{gold_path}"
dfG = pd.read_csv(project_root/'data'/'gold'/'starG.csv')
dfG

,identifier,class,full_class,effective_temperature,log_surface_gravity,metallicity_fe_h,radial_velocity,redshift
0,300702165|2015/01/19,K,K4,4729.36,4.741,-0.128,42.15,0.000141
1,215109|2011/10/23,G,G8,4642.57,4.662,-0.363,36.61,0.000122
2,18112111|2011/12/18,K,K3,4664.49,4.690,-0.207,35.04,0.000117
3,367412199|2015/10/07,G,G9,4960.44,4.613,-0.262,-35.46,-0.000118
4,18112179|2011/12/18,G,G8,5371.04,4.296,-0.248,-29.91,-0.000100
...,...,...,...,...,...,...,...,...
49995,686002046|2018/10/30,F,F2,6061.88,3.811,-0.240,9.94,0.000033
49996,381902037|2015/11/02,F,F2,6033.30,4.190,-0.458,35.12,0.000117
49997,381902043|2015/11/02,G,G9,5066.79,3.210,-0.247,-26.94,-0.000090
49998,254204018|2014/10/14,G,G7,5571.65,4.073,0.435,1.68,0.000006
49999,724304018|2019/02/07,G,G7,5558.18,4.045,0.406,4.15,0.000014

In [13]:
# # SETUP
# import pandas as pd
# from pathlib import Path
# from datetime import datetime

# # PATHS (using your exact structure)
# project_root = Path().absolute().parent
# gold_path = project_root / 'data' / 'gold'
# gold_path.mkdir(parents=True, exist_ok=True)  # Ensure directory exists
# input_csv = gold_path / 'starG.csv'  # Existing data
# new_csv = gold_path / 'starG.csv'  # New data to merge
# output_csv = gold_path / 'starG.csv'  # Final output

# # VALIDATION FUNCTION
# def validate_columns(df, required_cols):
#     missing = [col for col in required_cols if col not in df.columns]
#     if missing:
#         raise KeyError(f"Missing required columns: {missing}")

# # LOAD DATA WITH VALIDATION
# required_columns = ['identifier', 'date', 'lamost']
# try:
#     df_existing = pd.read_csv(input_csv, parse_dates=['date']) if input_csv.exists() else pd.DataFrame()
#     validate_columns(df_existing, required_columns) if not df_existing.empty else None
    
#     df_new = pd.read_csv(new_csv, parse_dates=['date'])
#     validate_columns(df_new, required_columns)

#     # MERGE STRATEGY
#     combined = pd.concat([df_existing, df_new])
    
#     # 1. Sort by date (newest first)
#     combined = combined.sort_values('date', ascending=False)
    
#     # 2. Remove duplicates - keeps first occurrence (most recent) for each identifier
#     combined = combined.drop_duplicates(subset=['identifier'], keep='first')
    
#     # 3. For repeated lamost IDs, keep most recent with complete identifier
#     combined = combined.sort_values(['lamost', 'date'], ascending=[True, False])
#     combined = combined.drop_duplicates(subset=['lamost'], keep='first')
    
#     # FILL MISSING VALUES (new data fills gaps in existing)
#     combined.update(df_new, overwrite=False)  # Only fills NaN values
    
#     # SAVE RESULT
#     combined.to_csv(output_csv, index=False)
#     print(f"✅ Successfully updated: {output_csv}")
    
# except KeyError as e:
#     print(f"❌ Column error: {e}")
#     print("Required columns: identifier, date, lamost")
# except Exception as e:
#     print(f"❌ Unexpected error: {e}")